### ISSUE TITLE
ReactJS Official Documentation cannot be accessed by a vast majority in Nigeria.

### ISSUE THREAD

**Issue by Echika** [reactjs/react.dev#6861]
### Summary

Whenever I try to visit the react website for my studies as a self paced frontend developer, I always get an error message saying "react.dev took too long to respond". I kept on trying for many months until I decided to contact several people telling them to visit the react.dev website. I was surprised to see the same report. Below is a screenshot of the error message. Please could you do something to help Nigerians like me solve this issue?

![Screenshot_2024-05-13-10-36-40-758_com android chrome](https://github.com/reactjs/react.dev/assets/85797519/a227ed0f-217f-4422-98e9-442e4493a112)

I'd be really grateful.

### Page

https://react.dev/

**Comment by aiKhalil08** [comment]
Hi. while waiting for an answer from someone on the react team, you can download a vpn to access the docs. Also facing the same issue in Nigeria.

**Comment by rickhanlonii** [comment]
Thanks for reporting, fwiw we're not blocking it. I think some countries/ISPs have blocked the IP we're hosted on. Trying to see what we can go to move where we're deployed to fix.

**Comment by eemanDigital** [comment]
I have been have this experience for quite a while now. Hope this is resolved on time. From Nigeria

**Comment by gaearon** [comment]
This has been a problem for a while. Can we set up a mirror or something in the meantime?

**Comment by Echika** [comment]
The Official React Documentation could be accessed through the installation of the VPN server. But I still had to report the problem. So pending the time this would be solved, you could as well install the VPN server.
Thanks.

**Comment by rickhanlonii** [comment]
This has been fixed, and I'll post a writeup in https://github.com/reactjs/react.dev/issues/6732.

**Comment by eemanDigital** [comment]
It has indeed been fixed. So, happy

**Comment by eemanDigital** [comment]
👍

Eeman reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by Precious-c** [comment]
Had this been really fixed. I still encounter the same issue
